spring.application.name=event-driven-marketplace
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/order,classpath:db/migration/inventory,classpath:db/migration/auth,classpath:db/migration/payment,classpath:db/migration/notification
app.retry.optimistic.max-attempts=3
app.retry.optimistic.backoff-millis=30

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/marketplace}
spring.datasource.username=${DB_USER:marketplace}
spring.datasource.password=${DB_PASSWORD}

app.security.jwt.public-key=${JWT_PUBLIC_KEY:file:./secrets/app.pub}
app.security.jwt.private-key=${JWT_PRIVATE_KEY:file:./secrets/app-pkcs8.key}

spring.config.import=optional:configtree:/run/secrets/


