spring.application.name=event-driven-marketplace
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/order,classpath:db/migration/inventory,classpath:db/migration/auth,classpath:db/migration/payment
app.retry.optimistic.max-attempts=3
app.retry.optimistic.backoff-millis=30