### GET request to example server
GET localhost:8080/actuator/health
###


POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "alice@test.io",
  "password": "password123"
}


### login alice
POST localhost:8080/api/auth/login
Content-Type: application/json

{"email": "alice@test.io", "password": "password123"}

> {% client.global.set("aliceToken", response.body.token); %}

### O1: aaaa x1
@productA =aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
POST localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

### V1: пустой items
@host =localhost:8080
POST {{host}}/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

{"items": []}

###
POST {{host}}/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

{}

### V3: productId не UUID
POST {{host}}/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

{"items": [{"productId": "not-a-uuid", "quantity": 1}]}

###
GET {{host}}/api/orders/not-a-uuid
Authorization: Bearer {{aliceToken}}


### V5: productId = null
POST {{host}}/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

{"items": [{"productId": null, "quantity": 1}]}

### V6: несуществующий товар
POST {{host}}/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

{"items": [{"productId": "dddddddd-dddd-dddd-dddd-dddddddddddd", "quantity": 1}]}

###
@o1 =110231
GET {{host}}/api/orders/{{o1}}
Authorization: Bearer garbage