### GET request to example server
GET localhost:8080/actuator/health
###


POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "alice@test.io",
  "password": "password123"
}


### login alice
POST localhost:8080/api/auth/login
Content-Type: application/json

{"email": "alice@test.io", "password": "password123"}

> {% client.global.set("aliceToken", response.body.token); %}

### O1: aaaa x1
@productA =aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
POST localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer {{aliceToken}}

{"items": [{"productId": "99999999-9999-9999-9999-999999999999", "quantity": -5}]}

> {% client.global.set("o6", response.body.id); %}

###
GET localhost:8080/api/orders/99999999-9999-9999-9999-999999999999
Content-Type: application/json
Authorization: Bearer {{aliceToken}}
